# Generated by Django 3.1.6 on 2021-03-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Permanent', 'permanent'), ('6Months', '6 months'), ('1Year', '1 year')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('job_contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Remote', 'remote'), ('Overseas', 'overseas'), ('Cork', 'cork'), ('Galway', 'galway'), ('Dublin', 'dublin')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Full Time', 'full time'), ('Part Time', 'part time'), ('20Hours', '20 hours')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.location'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.schedule'),
        ),
    ]
