# Generated by Django 3.2 on 2021-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210414_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(choices=[('Permanent', 'permanent'), ('6 Months', '6 months'), ('1 Year', '1 year')], max_length=15),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(choices=[('Full Time', 'full time'), ('Part Time', 'part time'), ('20 Hours', '20 hours')], max_length=15),
        ),
    ]
